# mysql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysport?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: aaaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

server:
  port: 9000
